#ifndef FUNCTIONS_H
#define FUNCTIONS_H

// DO NOT EDIT THIS FILE

int count_digit_occurrences(int, int);
bool has_repeated_digits(int);
int count_valid_numbers(int, int);
bool is_valid_range(int, int);

#endif  // FUNCTIONS_H
